name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.3.0
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.8.1
  injectable: ^2.4.2
  connectivity_plus: ^6.1.2
  flutter_secure_storage: ^9.2.2
  lottie: ^3.1.3
  typewritertext: ^3.0.9
  infinite_scroll_pagination: ^4.1.0
  rxdart: ^0.28.0
  google_maps_flutter: ^2.10.0
  flutter_svg: ^2.0.17
  pinput: ^5.0.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  firebase_analytics: any
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.2.1
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1


flutter:
  uses-material-design: true

  assets:
    - assets/anim/
    - assets/images/

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/lobster/Lobster-Regular.ttf
    - family: Cyrano
      fonts:
        - asset: assets/fonts/Cyrano.otf
    - family: Lofty
      fonts:
        - asset: assets/fonts/lofty-goals.regular.ttf
    - family: Hiatus
      fonts:
        - asset: assets/fonts/Hiatus.ttf
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
        - asset: assets/fonts/manrope/Manrope-Light.ttf
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
        - asset: assets/fonts/manrope/Manrope-Regular.ttf

