name: todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.3.0
  dio: ^5.7.0
  retrofit: ^4.4.1
  pretty_dio_logger: ^1.4.0
  json_annotation: ^4.8.1
  injectable: ^2.4.2
  connectivity_plus: ^6.0.5
  flutter_secure_storage: ^9.2.2
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  retrofit_generator: ^8.2.1
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/anim/
